#!/bin/sh

# LAUNCHERS
 
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

# BSPWM Configuration

bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       3
bspc config left_padding         3
bspc config right_padding        3
bspc config single_monocle       true
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# BSPWM Colouring

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


# Single Monitor

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Dual Monitor

#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5
#bspc monitor eDP-1 -d 6 7 8 9 10

# Fullscreen Applications

#bspc rule -a Archlinux-tweak-tool.py state=fullscreen
bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
#bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

# Floating Applications

bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
#bspc rule -a Xfce4-terminal state=floating

# Tiled Applications

bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
#bspc rule -a nextcloud-client state=tiled

# Open Applications on Specific Workspaces

bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a thunderbird desktop='^9' follow=on
bspc rule -a firefox desktop='^8' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
bspc rule -a Xed desktop=2 follow=on
#bspc rule -a Htop desktop='^8' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a anydesk desktop='^5' follow=on
bspc rule -a xfce4-terminal='^5' follow=on
bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
bspc rule -a LibreWolf desktop='^4' follow=on
bspc rule -a transmission-gtk desktop='^7' follow=on
bspc rule -a Nemo desktop='^1' follow=on
#bspc rule -a discord desktop='^9' follow=on
bspc rule -a Spotify desktop='^10' follow=on
#bspc desktop -f,node -d 5 xfce-terminal

# Workspaces



# Spotify Fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

# Polybar Hidden when Fullscreen for Vlc, Youtube, Mpv ...

# Find Out the Name of Your Monitor with Xrandr

#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

### External Rules

## Pseudo Automatic Mode: Always Splits Focused Window when Opening New Window

#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode

## Adjust New Window: Splits Biggest Windows to Keep Windows About the Same Size

#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window



